{
 "title": "Screeps",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "server", "label": "Server", "query": "stats.gauges.*" },
   { "name": "room", "label": "Room", "query": "stats.gauges.$server.rooms.*" }
  ]
 },
 "panels": [
  {
   "title": "CPU Usage",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 0 },
   "targets": [
    {
     "target": "stats.gauges.$server.cpuPercent"
    }
   ]
  },
  {
   "title": "CPU / Creep",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 0 },
   "targets": [
    {
     "target": "divideSeries(stats.gauges.$server.cpu, stats.gauges.$server.creeps)"
    }
   ]
  },
  {
   "title": "CPU Bucket",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 2, "x": 8, "y": 0 },
   "targets": [
    {
     "target": "keepLastValue(stats.gauges.$server.bucket)"
    }
   ]
  },
  {
   "title": "Tick Rate",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 10, "y": 0 },
   "format": "s",
   "valueName": "avg",
   "targets": [
    {
     "target": "invert(movingAverage(perSecond(keepLastValue(stats.gauges.$server.tick)),200))"
    }
   ]
  },
  {
   "title": "Creeps",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 5, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "target": "keepLastValue(stats.gauges.$server.creeps)"
    }
   ]
  },
  {
   "title": "Local Defenders",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 17, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "target": "aliasByNode(sumSeries(stats.gauges.$server.rooms.*.creepsCount.local-defender), 4)"
    }
   ]
  },
  {
   "title": "Remote Defenders",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 19, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "target": "aliasByNode(sumSeries(stats.gauges.$server.rooms.*.creepsCount.remote-defender), 4)"
    }
   ]
  },
  {
   "title": "L Harvesters",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 22, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "target": "aliasByNode(sumSeries(stats.gauges.$server.rooms.*.creepsCount.long-distance-harvester), 4)"
    }
   ]
  },
  {
   "title": "Sieged Rooms",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 17, "y": 3 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "target": "alias(sumSeries(keepLastValue(stats.gauges.$server.rooms.*.underSiege)), \"Sieged Rooms\")"
    }
   ]
  },
  {
   "title": "L Trucks",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 19, "y": 3 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "target": "aliasByNode(sumSeries(stats.gauges.$server.rooms.*.creepsCount.long-distance-truck), 4)"
    }
   ]
  },
  {
   "title": "Total Energy Storage",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 3 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "target": "alias(scale(sumSeries(#A),0.000001), \"Energy Storage Total\")",
     "targetFull": "alias(scale(sumSeries(aliasByNode(stats.gauges.$server.rooms.*.storedEnergy,4)),0.000001), \"Energy Storage Total\")"
    }
   ]
  },
  {
   "title": "GCL",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "target": "stats.gauges.$server.gcl" }
   ]
  },
  {
   "title": "GCL Progress",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 5, "x": 15, "y": 6 },
   "targets": [
    {
     "target": "divideSeries(keepLastValue(stats.gauges.$server.gclProgress), keepLastValue(stats.gauges.$server.gclProgressTotal))"
    }
   ]
  },
  {
   "title": "Time to next GCL",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 6 },
   "format": "d",
   "valueName": "avg",
   "targets": [
    {
     "target": "alias(divideSeries(#B, #A), 'Rem')",
     "targetFull": "alias(divideSeries(alias(keepLastValue(diffSeries(stats.gauges.$server.gclProgressTotal, stats.gauges.$server.gclProgress)), 'Progress to go'), alias(scale(movingAverage(perSecond(keepLastValue(stats.gauges.$server.gclProgress)), 500), 86400), 'GCL / 24hr (avg)')), 'Rem')"
    }
   ]
  },
  {
   "title": "Energy Generation",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 7 },
   "targets": [
    {
     "target": "aliasByNode(#C,4)",
     "targetFull": "aliasByNode(divideSeries(movingAverage(derivative(stats.gauges.$server.rooms.*.energyAccumulated),1000),movingAverage(derivative(stats.gauges.$server.tick), 1000)),4)"
    }
   ]
  },
  {
   "title": "Rooms",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 9 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "target": "stats.gauges.$server.roomsCount"
    }
   ]
  },
  {
   "title": "Spawns Load",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 11 },
   "targets": [
    {
     "target": "aliasByNode(movingAverage(stats.gauges.$server.rooms.*.spawnsUsage,100),4)"
    }
   ]
  },
  {
   "title": "GCL Progress",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "refCount": 1,
     "target": "alias(#D,\"GCL Progress / tick\")",
     "targetFull": "alias(movingAverage(keepLastValue(divideSeries(keepLastValue(derivative(keepLastValue(stats.gauges.$server.gclProgress))), derivative(keepLastValue(stats.gauges.$server.tick)))),100),\"GCL Progress / tick\")"
    }
   ]
  },
  {
   "title": "RCL",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 15 },
   "targets": [
    {
     "refCount": 1,
     "target": "aliasByNode(keepLastValue(stats.gauges.$server.rooms.$room.rclP), 4)"
    }
   ]
  },
  {
   "title": "Energy Generation",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "refCount": 1,
     "target": "aliasByNode(keepLastValue(divideSeries(#C, #D)), 4)",
     "targetFull": "aliasByNode(keepLastValue(divideSeries(derivative(movingAverage(stats.gauges.$server.rooms.*.energyAccumulated,100)), derivative(movingAverage(stats.gauges.$server.tick,100)))), 4)"
    }
   ]
  },
  {
   "title": "Energy Storage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(stats.gauges.$server.rooms.*.storedEnergy,4)"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "target": "alias(movingAverage(keepLastValue(stats.gauges.$server.cpuPercent),20),\"CPU\")"
    }
   ]
  },
  {
   "title": "mCPU/Creep over time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "target": "alias(scale(divideSeries(movingAverage(keepLastValue(stats.gauges.$server.cpu),10), movingAverage(keepLastValue(stats.gauges.$server.creeps),10)),1000), \"mCPU\")"
    }
   ]
  }
 ]
}